import { type ComponentPropsWithoutRef } from "react";
import { useAtomValue } from "jotai";
import { classNames } from "@/utils";
import { type OFormContextProps, type MFormContextProps, type NFormContextProps } from "@/store/1-atoms/2-file-mani-atoms";
import { AccordionWithTrigger } from "@/ui/motion-primitives";
import { DetectionContent_Web, DetectionContent_W32 } from "./2-detection-content";

export function InFormOptions({ n_mCtx, className, ...rest }: { n_mCtx: NFormContextProps | MFormContextProps; } & ComponentPropsWithoutRef<'div'>) {
    const formOptionsCtx = n_mCtx.maniAtoms?.[n_mCtx.formIdx];
    if (!formOptionsCtx) {
        return null;
    }
    const ctx: OFormContextProps = { maniAtoms: n_mCtx.maniAtoms, oAllAtoms: formOptionsCtx, formIdx: n_mCtx.formIdx };
    return (
        <div className={classNames("text-xs flex flex-col items-start gap-1 select-none", className)} {...rest}>
            <div className="font-semibold">
                Additional options
            </div>

            <FormDetection ctx={ctx} />
            <div className="">
                Lorem ipsum dolor sit amet consectetur, adipisicing elit. Beatae consectetur veritatis ducimus ipsam voluptatibus pariatur tempore nemo explicabo iure suscipit non similique at, veniam quo itaque voluptate minus aut et!
                Quisquam, molestias tenetur quidem magni fuga vero perferendis ipsam voluptas eum saepe beatae cupiditate ducimus? Tenetur ipsam aspernatur cum, ea excepturi eos! Obcaecati illum suscipit, eveniet nesciunt voluptatum possimus alias.
                Velit maxime autem totam molestias rerum mollitia praesentium tenetur ipsum amet modi ut debitis temporibus neque veniam, animi eos necessitatibus! Laboriosam magnam sunt sed facere rerum non architecto quidem maiores!
                Sit, libero nisi qui reiciendis unde fugit eaque totam ratione, obcaecati corporis vel iure officia? Amet ut omnis non inventore! Rem debitis soluta doloremque nemo accusantium, dolor atque temporibus illo?
                Itaque, voluptas aliquam voluptatum consequuntur ad exercitationem impedit, in facere error esse ab aut! Reiciendis earum officia impedit! Et similique suscipit quisquam sit recusandae eum cupiditate nihil quia possimus voluptatem!
                Blanditiis cumque numquam voluptatem qui aspernatur eveniet, necessitatibus, quaerat ab dolorem nesciunt at earum similique deleniti exercitationem, assumenda ullam modi illum corporis minus a perferendis enim? Aspernatur debitis amet laboriosam.
                Corporis dolore ipsam magnam, omnis laborum natus? Temporibus dolor animi nihil quibusdam ab ratione, enim eum quam non optio debitis. Beatae cupiditate, laudantium accusantium inventore obcaecati labore officiis dicta maiores?
                Debitis explicabo porro officiis vitae qui odio, minima error, nesciunt reprehenderit perspiciatis cum a optio. Quaerat sapiente ut obcaecati amet sint reiciendis voluptatem similique facere quo dicta! Sint, quod repellat.
                Eveniet sint repudiandae expedita illum illo suscipit delectus saepe tempora voluptatum. Minus quod aliquid ratione repudiandae numquam. Molestias exercitationem nisi eos. Veritatis eaque quaerat nam autem doloribus reiciendis ea dignissimos.
                Voluptate iure exercitationem molestias alias natus magnam ipsam quod sit eveniet, dolores animi qui minus accusantium blanditiis consectetur. Eligendi, nesciunt labore cupiditate nihil quod magni cum? Earum fuga veniam maxime!
                Doloremque in quibusdam sed architecto pariatur provident perferendis sit molestiae eligendi recusandae consequatur veniam similique perspiciatis rem, non deleniti doloribus libero suscipit inventore illo accusamus amet voluptatum ipsam? Doloremque, aliquam!
                Nisi earum, natus sed in harum, ullam voluptates pariatur velit quas aliquid labore praesentium error! Quasi quaerat quos tempore voluptatem expedita fuga molestias, ad, explicabo impedit sequi possimus quas! Porro?
                Vitae, omnis. Provident, nam, tenetur eaque ullam doloremque modi corrupti blanditiis natus dicta possimus accusantium praesentium inventore quibusdam odit consequuntur cumque architecto alias error sunt accusamus. Aperiam et ducimus repellat.
                In incidunt eaque, placeat quasi, delectus exercitationem repudiandae modi ratione optio veritatis repellendus nobis expedita dolores eius ipsam earum vero voluptatum quaerat quidem illum atque soluta! Culpa excepturi assumenda ipsum.
                Exercitationem ea accusamus, ducimus fugit at doloremque nobis sapiente. Ipsum fugit consequatur ipsam numquam maxime ad blanditiis magni! Ipsa debitis assumenda perferendis eaque exercitationem corporis perspiciatis facilis! Dignissimos, eaque iure!
                Labore possimus sint quo laboriosam quidem, reiciendis, accusamus autem aut eaque culpa aliquam quaerat, non provident impedit ab nihil incidunt. Itaque quasi accusamus commodi praesentium quam voluptatem id quas adipisci.
                Odit dolor nulla corrupti possimus distinctio sit voluptatibus iure a perferendis! Fuga nisi fugiat voluptatem consequatur et sed nulla enim quaerat, aperiam odio, repudiandae perspiciatis at aspernatur ut dolore voluptatibus.
                Officiis sequi iure aperiam dolorum. Non reiciendis deserunt aliquid, molestiae tenetur sed cupiditate nisi, possimus, veritatis officiis repellat iusto exercitationem quaerat. Fuga, atque pariatur! Consectetur quia dicta voluptas recusandae accusantium?
                Pariatur corrupti nostrum officiis expedita accusantium amet sint laborum nisi rem recusandae reprehenderit, autem dicta incidunt. Quibusdam error excepturi repudiandae, numquam qui corporis ab placeat facere ducimus velit, assumenda itaque.
                Praesentium unde consequatur voluptatum porro itaque explicabo necessitatibus sunt aut suscipit placeat rem, voluptates quia vel similique quidem quae quos odio consequuntur. Aliquid cum, ratione adipisci iusto consectetur suscipit ea?
                Temporibus quibusdam, explicabo non laboriosam mollitia aut vel, ea quis quidem accusamus, incidunt maiores minima consequuntur unde asperiores! Repudiandae quas dolor dolores suscipit maxime quae velit fugit exercitationem aut nemo.
                Cumque iusto provident harum, culpa autem totam, sit nisi officiis doloremque necessitatibus saepe doloribus eos voluptatibus consequuntur et suscipit at itaque! Sequi, natus nobis laudantium omnis at vel quas fugiat!
                Omnis architecto corporis natus dolore deleniti consequuntur pariatur molestiae quasi at unde, voluptatem reprehenderit aliquam aliquid eum nam accusantium placeat mollitia quaerat labore tempore eveniet ea inventore perspiciatis. Ipsam, eum?
                Qui sequi enim consequatur? Velit laudantium obcaecati consectetur sed voluptate temporibus, placeat quidem sunt! Numquam suscipit explicabo amet veniam eius laudantium, sed quisquam error quaerat officia, voluptas vitae quo odit.
                Repellat inventore nemo dignissimos sunt beatae, reiciendis minus atque laboriosam! Molestias et nulla aliquid quisquam eveniet iste? Necessitatibus consectetur nulla numquam beatae repellendus dignissimos ex repudiandae quae iusto, aspernatur atque!
                Aut minus voluptate saepe qui! Delectus quasi laboriosam explicabo dicta rem ratione quibusdam laborum nihil repudiandae tempora, magnam earum! Deleniti, commodi reprehenderit nesciunt cumque laudantium ipsa odit perferendis necessitatibus nisi!
                Itaque dignissimos quos a aut dolores maxime voluptate quo suscipit esse maiores amet exercitationem, ratione adipisci repellat nihil sed, inventore consequatur quas est fugit voluptas dolorum excepturi earum. Nihil, inventore?
                Aliquid sed quidem velit fugiat quam, excepturi unde nemo error quaerat eos quibusdam labore, pariatur, doloribus praesentium similique facilis! Eius ea, modi iure quod possimus inventore expedita hic quo laborum!
                Consequatur dignissimos sint labore quam minima reprehenderit suscipit id est libero. Commodi iste rerum ipsa id neque tenetur vel a, harum, exercitationem, illum ducimus beatae magni voluptatum placeat sint perferendis.
                Tempora tenetur a impedit ratione recusandae eligendi consequatur excepturi nihil sint iste eveniet nisi modi est rerum quo, quaerat culpa expedita. Eveniet, cupiditate fuga assumenda eius laboriosam illum repellat nemo.
                Molestias doloremque ad obcaecati ea expedita maxime rerum, omnis, inventore voluptatibus, nulla repellendus impedit. Voluptatibus odio asperiores repellendus perspiciatis atque officiis explicabo maiores quasi? Reiciendis placeat eos possimus laudantium qui.
                Laboriosam quidem maxime placeat unde adipisci. Non, magni sapiente nisi beatae illum nemo voluptatum ullam voluptatem delectus obcaecati. Recusandae ratione mollitia vitae nam eaque. Velit cum rerum doloremque corporis ut.
                Earum quidem et natus id illum minus vitae atque! Molestiae, eius voluptates sint odit, commodi dolor enim inventore repudiandae maxime, sit labore deserunt. Itaque, repellat soluta. Dignissimos eius debitis iste.
                Nam quidem amet laboriosam repellat ratione! Recusandae voluptatibus quisquam, laboriosam, explicabo adipisci asperiores in accusantium totam eaque iure ipsam animi, deserunt ducimus cumque debitis cum? Voluptas quas alias deleniti maxime.
                Labore eius a et autem, eaque veritatis libero vel quod eos doloremque placeat iure distinctio quasi tenetur hic, fugit deleniti? Asperiores est at, explicabo saepe sed illum magnam impedit corporis?
                Tempore reiciendis fugit, tempora dicta accusantium excepturi cumque ipsum, officia magni error perferendis! Omnis provident aspernatur eaque, sed dolor corrupti rem assumenda quaerat magnam nostrum maiores veniam eos itaque dolores.
                Culpa, veritatis. Mollitia, labore tempora! Possimus odio impedit, laudantium, ipsum quidem molestias corrupti tempora aut quaerat libero dolores beatae quia nam atque veniam eaque soluta adipisci suscipit nisi. Harum, quis.
                Qui ad expedita similique consequuntur! Beatae corporis illo quasi, excepturi dolorem nesciunt obcaecati provident libero optio, tenetur adipisci error expedita architecto voluptatum facere perspiciatis. Mollitia architecto facilis minima dolorum nemo.
                Voluptatum itaque corporis provident tempora impedit reiciendis deleniti. Itaque a optio facere quo veniam laborum suscipit vel quas libero, commodi nemo earum saepe recusandae. Laboriosam eos cumque expedita cum ipsam.
                Ab facere rem ipsa sequi doloremque molestias dicta a laboriosam! Laudantium a repudiandae, totam nisi temporibus, dolorem numquam tempora assumenda nemo earum, minima dignissimos adipisci officia mollitia commodi quis suscipit.
                Culpa, facilis perspiciatis architecto officia molestias consectetur veritatis impedit porro autem enim laborum ea deleniti at atque totam non alias consequuntur asperiores amet ad. Numquam laudantium alias unde saepe modi!
                Ducimus minus nobis error impedit mollitia aperiam nulla, qui, doloremque repellendus consequatur neque. Dolores a esse tempore optio, soluta veritatis, ratione harum quos consequatur ipsum, saepe reiciendis quia neque perspiciatis.
                Recusandae corrupti odit repellendus illum illo tenetur, quae numquam? Non voluptatum ipsum incidunt, provident qui sunt minus amet? Debitis corrupti architecto aperiam quasi optio, adipisci tempora totam vitae commodi laudantium.
                Eum fuga incidunt dignissimos blanditiis! Distinctio voluptatem aperiam praesentium. Rem nisi et numquam quas laudantium sed delectus cupiditate voluptatem sint doloribus fuga quam itaque consectetur, doloremque, libero ullam nostrum! Quo.
                Aliquid, consequatur debitis repudiandae delectus quo distinctio asperiores blanditiis. Dignissimos non cumque culpa quis libero, fuga, tempore earum delectus, mollitia repudiandae aliquam. Illo commodi in iure iusto dolores ipsa exercitationem?
                Tenetur veritatis, odit perferendis modi esse repellendus veniam repudiandae id vel, voluptate nobis illo quisquam et sunt ad unde. Eius sint illum corporis soluta sit quis commodi delectus veniam at!
                Velit harum eaque, omnis consectetur veritatis qui explicabo accusantium suscipit placeat eos ipsum necessitatibus repudiandae ut reiciendis asperiores, praesentium nisi soluta ab quis dignissimos quam? Quaerat nobis voluptates veniam quidem.
                Quidem natus pariatur assumenda recusandae suscipit. Aperiam dignissimos accusamus delectus cumque error ab eum hic pariatur optio laborum cum natus, vero iusto illo at asperiores corporis possimus? Tenetur, sequi! Earum.
                Aut minus molestiae quis modi officiis corporis rem aliquam excepturi, dignissimos voluptatum magni beatae tempora provident iure animi aspernatur tenetur voluptatem a soluta nam. Minima maxime incidunt voluptatem voluptate natus!
                Quia nihil labore consequuntur excepturi adipisci qui, enim velit, eligendi veniam voluptates id ad quo quos eveniet similique magni harum! Autem libero fuga, eos asperiores cumque explicabo dicta illum in.
                Accusamus, doloribus! In aliquid dolor repellat quos tempora ducimus qui labore dolores rerum. Culpa ipsam voluptatem vel amet nulla animi quidem esse perspiciatis, nam dicta! Nihil molestiae velit fugiat hic.
                Modi esse id quo sint perspiciatis ad, eaque eligendi doloremque reprehenderit assumenda ipsam, nisi ex aliquid, nemo cum vitae rerum adipisci qui praesentium fugiat. Mollitia qui eaque veritatis architecto voluptas?
                Nesciunt, ipsam praesentium expedita distinctio consequuntur nobis voluptatum dolorem maiores laudantium, explicabo dolores cum! Quidem consequatur ipsum repudiandae impedit ea possimus assumenda id laboriosam, molestiae enim, tempora omnis atque dolorem?
                Sint totam, ab temporibus nulla eius illo doloremque commodi cum nostrum minima ad, tenetur quibusdam quisquam, minus iure magni reiciendis laboriosam dicta aliquid? Iste quo rerum fugiat aperiam qui quae?
                Sequi quos suscipit, voluptatem debitis atque illum molestias perspiciatis saepe, a placeat consequuntur consectetur accusamus ut rerum minima tempore cum facilis libero rem sapiente quasi? Deserunt eligendi aspernatur veniam eum.
                Quae ex nam illo dolores tenetur, accusantium dolor accusamus fuga mollitia numquam temporibus nesciunt vel corporis, quisquam maiores excepturi ipsam architecto labore sapiente dolorum? Doloribus, porro ex. Maiores, deleniti similique?
                Dignissimos excepturi tenetur omnis facere fugiat doloremque in molestiae molestias ex voluptatibus amet et quaerat consequatur vitae tempore, perferendis quis hic dolores beatae aliquam laboriosam facilis? Beatae maiores nemo aspernatur!
                Temporibus maiores distinctio quidem soluta rem eos molestiae consequatur blanditiis exercitationem. Inventore fugiat ab quibusdam numquam tempore fugit odit culpa est quam aperiam! Atque obcaecati, modi perferendis accusantium neque fugiat?
                Facere deserunt aliquam mollitia vel odio eos delectus magnam corrupti reprehenderit, temporibus enim. Sunt ut eius adipisci totam dolorem quo, praesentium a eum consequatur itaque dicta ea, doloremque sequi libero!
                Commodi cupiditate fugiat neque ullam aliquid accusantium quas similique consectetur, accusamus est praesentium qui asperiores officia, in assumenda obcaecati necessitatibus voluptatem quo dolores ea? Ullam harum nulla quis dolore nesciunt?
                Quis dicta porro officia vitae nobis quo cupiditate nihil quasi nisi dolorem aut, asperiores eveniet ipsa veritatis eaque dolore cumque, molestias tempora. Quod placeat tenetur modi dolorum voluptates odio quisquam?
                Minus fugit distinctio nemo ullam, consectetur suscipit fugiat iste illum cum aliquam officiis odio consequuntur rem quos explicabo nihil aspernatur dolorem soluta, totam corporis. Perferendis illum deserunt dolorem tempore iusto.
                Voluptas accusantium nihil necessitatibus laudantium eius tempore modi, molestiae sit explicabo! Consequatur tempore eius assumenda accusantium, enim, ut ad soluta dolorem unde expedita, eligendi sit. Sunt laboriosam quibusdam harum blanditiis.
                Et recusandae inventore fuga officia rem, veritatis consequuntur laudantium suscipit non corporis aliquid! Magnam corrupti laborum perspiciatis maiores est sint enim, recusandae, dolorem voluptas reprehenderit, totam praesentium alias ab non?
                Repellat minima ullam aliquam! Optio, libero magni. Modi rerum tempora fugiat possimus, sapiente aperiam exercitationem repudiandae corporis et numquam eaque iure ullam sequi explicabo delectus officia autem doloremque repellat earum!
                Quam minus dignissimos magnam quaerat corrupti laborum et quos aperiam rem nostrum! Eos reiciendis quis libero officia eius iusto, totam voluptates recusandae mollitia repellendus optio illo, dicta fuga, nihil veritatis?
                Assumenda adipisci dolore modi, iure atque laborum maiores, delectus reiciendis optio, expedita recusandae numquam animi! Libero autem dolores maxime nobis unde, mollitia vero dolorum enim repellendus ipsum, corrupti sapiente consequuntur!
                Asperiores, quibusdam. Rerum consequuntur veritatis cupiditate. Mollitia et dicta nisi fuga nam? A culpa, quasi distinctio, nihil repellat, sunt aut explicabo ipsum nostrum commodi eos harum magni doloremque laudantium! Recusandae?
                Suscipit aut facilis beatae perspiciatis maxime, recusandae ea natus sit error consequatur ullam dolore rerum? Dolore ad illo magni, sit nesciunt, deserunt odit obcaecati placeat animi soluta quam. Incidunt, sunt?
                Ipsa accusamus aliquam, porro velit vero nemo maxime saepe. Delectus commodi a eligendi vero numquam maxime, magnam consequuntur dolorem, unde, ducimus quis doloremque fuga aliquam quaerat temporibus molestiae recusandae animi.
                Enim eos odio neque ipsa animi pariatur ducimus non itaque fugiat, ut, esse id distinctio. Asperiores maxime libero officiis unde cumque in deserunt amet. Veniam adipisci placeat consectetur culpa alias.
                Nulla quidem, architecto minus quas esse corporis unde necessitatibus ratione porro vitae a. Asperiores debitis sint, est enim sed nobis. Delectus nesciunt ea esse qui expedita. At velit laboriosam nihil.
                Temporibus tempora voluptas autem illum delectus ratione voluptatem a vitae, quas, commodi laborum eius quibusdam distinctio rerum alias itaque fuga ullam ipsum iure consectetur neque provident. Vitae aliquid dolor et.
                Perferendis, iusto totam laudantium rerum adipisci soluta molestias quasi quas provident, sed incidunt dolor porro est ab at animi dolorum eligendi nam officia amet molestiae culpa alias. Praesentium, modi magnam!
                Cupiditate, veritatis. Ducimus, quis? Ea, eum? Optio reiciendis aliquid error dolorum, harum explicabo dolor iure quo ad aliquam cupiditate atque quasi veritatis deserunt in facere unde voluptatum voluptate ea rerum!
                Ab, voluptatum praesentium. Quae, quas possimus culpa aperiam facilis natus quam ea sunt corporis hic cupiditate nobis quod dolore. Adipisci reprehenderit perferendis beatae odit praesentium. Enim nam recusandae suscipit? Natus?
                Animi, tempora fugiat. Ad aut quisquam porro nostrum esse deleniti pariatur deserunt, asperiores ducimus blanditiis earum voluptatum consequatur suscipit cum expedita commodi odit perferendis quos, mollitia, tenetur error repellat est!
                Fugit inventore nesciunt debitis tempora dicta accusantium, saepe quisquam a laudantium? Aut, facilis in ad quisquam quia neque cupiditate tempore ipsa ex voluptas itaque quo eos hic. Similique, nobis quos!
                Culpa veniam quia non qui consequatur unde? Deserunt est expedita vitae praesentium maiores ipsam, nisi assumenda modi numquam nobis blanditiis temporibus ad esse ullam mollitia ab dolore rerum suscipit quas?
                Recusandae, maxime atque rem, quibusdam culpa pariatur asperiores consequatur tenetur tempore tempora accusantium. Et beatae, nesciunt est corporis odio incidunt adipisci, vel officia rerum accusantium animi! Libero provident aliquam iure.
                Nostrum modi eum impedit quam vero deleniti, ullam nisi illum laudantium nemo itaque dicta nam dolore voluptatum praesentium veritatis libero consectetur mollitia quaerat quisquam tempora, illo eius expedita quis? Odit.
                Ullam reiciendis ratione, perspiciatis voluptas eveniet cupiditate deleniti nisi repudiandae, aut dignissimos cumque voluptates aliquam animi incidunt sapiente nostrum alias ab molestias velit culpa a est exercitationem iure officiis! Quisquam.
                Dolorum expedita voluptatibus earum at inventore, tempore saepe consectetur veniam rerum placeat assumenda magni soluta ducimus nam sunt deleniti neque, atque, nobis velit! Et dolore excepturi perferendis, commodi numquam omnis.
                Adipisci sint vitae voluptas impedit nisi accusamus dolorem quos unde officia omnis id temporibus ducimus dignissimos, nihil dolor laboriosam eius dolorum eaque ullam illum ipsam delectus nemo blanditiis. Nobis, id.
                Nostrum illo non dolores error temporibus commodi aperiam labore id doloribus officiis ea, impedit maiores! Suscipit, libero voluptatum? Eaque ab ea pariatur vel quibusdam modi illum neque voluptatem facilis porro.
                Veritatis doloribus aliquid maiores esse suscipit sint inventore quisquam asperiores minus quidem corrupti enim, iure, expedita id necessitatibus voluptatum ipsam autem at consequatur velit voluptatibus libero reprehenderit incidunt! Distinctio, atque?
                Suscipit ipsa alias reiciendis laudantium rerum maxime deserunt neque in labore pariatur. Velit, quos doloribus! Ut veritatis corrupti, maiores suscipit, autem distinctio, alias commodi placeat provident quidem porro eligendi cum.
                Dolorum maiores, doloremque illum consequuntur expedita ipsum ab tenetur facere dolorem dignissimos, fugit placeat autem commodi cum asperiores blanditiis enim quae explicabo ullam sit magni, excepturi nam nesciunt error! Esse.
                Maiores qui voluptates facilis repellendus autem temporibus pariatur nisi amet ipsam, quis eveniet blanditiis, suscipit molestiae iusto, repellat cupiditate? Minima natus incidunt perferendis eligendi assumenda alias harum at officia dicta?
                Illum corporis praesentium distinctio voluptatem sapiente voluptate ea, adipisci dolore dicta mollitia in cupiditate. Voluptatem omnis soluta dicta aspernatur. Quasi quo repudiandae sapiente voluptates facilis error suscipit esse et! Explicabo.
                Dolore, officiis porro? Culpa facere quia necessitatibus nesciunt magni recusandae excepturi ipsam mollitia blanditiis, rerum quae odio minima tempore deleniti nisi accusantium quod, laudantium aut quaerat? Placeat ut quos id.
                Itaque ducimus temporibus maiores laboriosam quisquam inventore impedit quo ut aliquid accusamus voluptas deserunt dolore perspiciatis eligendi eaque ipsam dolorum esse repellendus, ab nam, ipsum similique tenetur iure. Illum, velit!
                Repudiandae, aliquam quos? Ut, a voluptates nisi aliquam harum error, distinctio ratione voluptatem repellendus vel esse ad! Harum, voluptate vero fuga at nulla magni quasi excepturi soluta! Asperiores, necessitatibus sunt!
                Possimus error suscipit laborum asperiores quis, reprehenderit optio animi corrupti nisi labore aliquam ab esse quae veritatis ad blanditiis. Esse quidem illo natus quisquam a dolore unde consequatur incidunt ex?
                Accusantium quasi obcaecati accusamus ipsum iusto quia amet, optio adipisci eum, illo molestias non facere rem quae. Veritatis maiores vitae incidunt recusandae amet mollitia, rerum, fugit unde consectetur voluptates numquam.
                Labore qui voluptates, itaque nisi saepe placeat illo animi eveniet obcaecati nemo aspernatur adipisci culpa officiis. Suscipit, quae a commodi voluptates aspernatur totam provident ratione corrupti amet adipisci quisquam. Sed.
                Distinctio, ea? Odit maxime laboriosam, sit, enim ducimus repudiandae amet iusto tenetur culpa ratione optio saepe alias libero animi soluta quibusdam eum. Ipsum est ex molestiae culpa laboriosam. Dolorum, deleniti.
                Iste aliquid, fugiat ad adipisci ipsa laudantium modi soluta, quis quisquam voluptate commodi asperiores? Eligendi aut, repellat quia iure dolorum harum nisi, tempora eos sapiente dolores necessitatibus eius, accusantium neque.
                Iste rerum, obcaecati dolorem architecto error dolore? Nesciunt illo doloribus possimus natus eius cumque, voluptates perspiciatis ipsa corporis unde eaque molestiae officiis quisquam iste a deleniti culpa. Libero, maxime minima.
                Soluta amet a nihil quaerat vero recusandae, praesentium veniam minus incidunt sunt accusamus, voluptatum tempore, eius saepe accusantium. Exercitationem, eligendi! Ducimus, molestiae architecto! Consequatur, a quo accusamus reiciendis aliquam quod!
                Officia, reprehenderit sed, quis accusantium molestias dolores maiores odit voluptates ducimus iste corporis at. Nostrum et aut tempore sint error, quae doloremque numquam consequatur sed cumque minus nulla voluptatibus nam.
                Neque et provident repudiandae velit dolorem voluptate deserunt! Natus fugit blanditiis assumenda ullam nemo, laudantium eos quam aliquid saepe iure libero quis eaque fugiat incidunt culpa quibusdam corrupti sapiente adipisci?
                Dolore illum totam aspernatur saepe eius delectus, optio expedita nostrum cupiditate. Maiores veniam optio quaerat eveniet dicta autem nesciunt inventore sapiente ex debitis. Ipsam quasi, eveniet consequatur id a quos.
                Blanditiis ipsum quam saepe, dolorem quisquam nesciunt mollitia laudantium vitae asperiores officia in est tempore excepturi odit reiciendis explicabo possimus cumque repellat qui voluptate iure amet maiores. Amet, corrupti laudantium?
                Adipisci provident accusamus, quaerat numquam esse voluptatum. Similique, ullam neque? Placeat blanditiis fuga aspernatur eius, atque doloremque voluptatibus quibusdam minus, iusto doloribus repudiandae excepturi vero ipsam cumque quasi in autem.
                Aliquid natus tenetur ullam voluptatum velit, numquam earum perspiciatis, ut odio dolorem totam. Ab explicabo excepturi alias quia beatae aut quo voluptatum minima id sunt, voluptas suscipit molestias aperiam voluptate!
                Accusamus natus atque aspernatur delectus, odio quisquam nisi eaque amet suscipit debitis exercitationem ipsa earum rerum quia pariatur. Explicabo incidunt aliquid, voluptatum minus modi eius molestiae corrupti possimus magnam eligendi?
                Reprehenderit quia sapiente corrupti deserunt iste nobis id! Perspiciatis ullam est nesciunt ipsam accusamus pariatur a minima cumque! Officia reiciendis voluptas impedit? Velit nostrum quasi explicabo quod aliquam impedit est.
                Reiciendis sequi maiores, in blanditiis quas itaque dolor voluptatem. Itaque dolore eaque nam laborum aliquid laboriosam ratione expedita neque quia soluta, praesentium atque consequuntur iusto reiciendis doloribus ducimus nulla blanditiis!
                Necessitatibus, molestias. Vitae esse ut, quam enim dolore suscipit iste autem praesentium quae eos! Accusantium incidunt repudiandae maxime repellendus, veniam veritatis recusandae natus consectetur asperiores assumenda. Odio minus libero officia!
                Aperiam amet est alias qui cupiditate eaque quos unde nulla voluptas autem placeat, corporis, architecto quod! Quia id doloribus officia! Aliquam nemo, sint eum incidunt doloribus rem vitae culpa dolore.
                Dolor sapiente corporis perspiciatis fuga dicta laboriosam ex doloribus, placeat omnis aut voluptatem, cumque culpa et nemo veritatis? Optio, debitis dolores repellendus porro ut facere quo molestias minima quidem explicabo?
                Saepe officia tenetur vel optio similique aspernatur esse facilis fuga, repellat quae in modi sequi, reprehenderit commodi quod, nam itaque soluta tempore culpa eligendi delectus? Asperiores nemo corporis laudantium provident.
                Illum, qui quibusdam! Dolorum ipsam eos, a tempore neque voluptatem debitis quisquam totam sequi illum? Amet, corporis non quidem doloremque ad dolores, itaque eligendi nemo cupiditate, repudiandae corrupti dignissimos doloribus?
                Voluptatibus quaerat incidunt saepe numquam beatae, veritatis in odit ipsam veniam nam obcaecati eum! Amet rem delectus quas repellendus, nulla doloremque maxime voluptatem omnis vero aliquam deleniti quis earum dolores.
                Tenetur laborum eum ea praesentium molestias ad ullam asperiores quam perferendis quia, quas sapiente reprehenderit tempore voluptates? Ullam, consectetur, soluta consequuntur ex fuga eveniet ipsum autem reiciendis hic omnis possimus?
                Sint excepturi, vel quasi ex fugit hic dicta voluptas ipsum magnam. Architecto nulla iusto, eligendi laudantium aperiam blanditiis, odio obcaecati quis at deserunt explicabo cumque expedita voluptatem neque rerum nemo.
                Recusandae quae laudantium, excepturi unde nisi dignissimos necessitatibus tenetur eveniet est tempora qui tempore eos voluptatum asperiores? Cum voluptatibus, iusto dolorum veniam, doloribus et itaque eligendi velit eius distinctio expedita.
                Et laboriosam odit cupiditate mollitia animi impedit esse harum? Maiores nisi iusto repudiandae nobis? Est eligendi nisi amet quaerat, quod pariatur explicabo maxime autem ipsam quia. Quia animi rerum fuga.
                Autem eius nemo odit culpa quia magni obcaecati quam, maiores quisquam explicabo id inventore perferendis rem earum. Eligendi, fuga. Exercitationem accusantium dicta eligendi vel esse repellendus officia laborum, velit unde?
                Soluta veniam voluptatum expedita? Aspernatur totam nihil quam illo fugiat, in esse dolore maiores placeat delectus nemo, ab libero cumque officiis sapiente earum! Sit mollitia quisquam sunt repellat numquam soluta?
                Vel in, voluptate eum molestias omnis odio a! Mollitia placeat natus iusto labore qui exercitationem veniam repudiandae voluptatum commodi incidunt quibusdam obcaecati sequi, doloribus voluptas soluta, eum voluptatem atque vel?
                Omnis aut porro ipsam eius officia expedita hic, laborum esse illo, tenetur, at eum perferendis laudantium mollitia eos dolore placeat possimus! Vitae magni commodi excepturi harum mollitia numquam laborum hic?
                Dolor voluptate repellat odit. Placeat odit incidunt rerum eos rem fuga quae, corporis praesentium beatae dolorum inventore similique repellendus corrupti. Blanditiis dignissimos, ducimus laudantium recusandae quaerat consequuntur quia ullam tempore.
                A nisi cupiditate perspiciatis pariatur ex ipsum similique eveniet nostrum dolorem commodi alias voluptatibus, ad quia. Reiciendis, obcaecati. Placeat repellendus laborum aliquid esse accusamus natus harum enim sint illum architecto!
                Corrupti repellat officia reiciendis impedit alias saepe tenetur laborum minima mollitia aliquid quaerat at, necessitatibus dolorum facere in. Officia possimus necessitatibus nisi a, modi labore reprehenderit nobis velit incidunt voluptas?
                Totam exercitationem consequatur sunt dolore nesciunt! Nihil aliquid eveniet rem quibusdam aperiam beatae illum officia fugiat ipsa excepturi nostrum veniam perspiciatis, laudantium aliquam quidem accusantium qui ea aspernatur mollitia velit.
                Quas reiciendis laudantium, minus cupiditate ipsam ipsa optio deserunt accusantium quisquam et velit modi rem eligendi inventore consequuntur enim. Cumque quas iure iste illum aliquid fugit similique, optio est dicta.
                Repellendus, ex. Iure reiciendis ipsam similique explicabo incidunt quidem ea fugiat doloribus aliquam facilis quam odio harum repudiandae consectetur, ex fugit repellat sint! Modi itaque aliquam vel saepe, quos neque?
                Dolore, aspernatur ratione molestias repellendus tempora, debitis nisi nam eaque similique temporibus reiciendis consequuntur recusandae ipsa blanditiis exercitationem nesciunt voluptates velit omnis nulla iusto facere mollitia illum! Mollitia, rem explicabo.
                Id quam molestiae dolor debitis. Rerum ipsa ad adipisci unde vel ut nulla sunt, qui aut fugit eligendi libero veniam eveniet non voluptas optio, quod corporis repellendus quis. Veritatis, inventore?
                Quos molestiae ad exercitationem veritatis. Distinctio vitae culpa minus facere similique velit nostrum id amet optio quas sint dolores officia, alias in? Vitae quas voluptatibus repudiandae voluptatum vel! Accusamus, ut.
                Accusamus non quia fugiat ipsam nemo voluptate error repudiandae ipsa ad minus impedit, quos dolore. Cupiditate quod voluptatum vel, a repellat animi fuga tempore pariatur fugiat voluptates officia illo provident.
                Iusto rerum aperiam debitis dolorem inventore, totam libero id, ratione odio quos ullam quis, adipisci dolorum cupiditate tenetur amet perferendis! Quidem, numquam cupiditate vero nobis culpa amet voluptatem facere perferendis!
                Cum ducimus maiores aperiam sapiente consequuntur nesciunt aut quis excepturi blanditiis. At tenetur, iusto consectetur placeat veritatis quasi obcaecati maxime, earum ut a cum eaque illum. Sit vero consectetur dolores.
                Sed maiores eius rem illo odit explicabo voluptatibus eos minima, quam, ut, quisquam suscipit eveniet. Dicta nemo dolores autem aspernatur exercitationem doloremque voluptate debitis eligendi, consequatur temporibus deserunt corrupti quam.
                Perferendis repellat, enim voluptatibus ad fuga eos officia, magni omnis asperiores ea laborum veniam voluptatum incidunt architecto nisi maxime consequuntur veritatis ipsum sunt exercitationem aspernatur, harum optio quibusdam soluta! Consequuntur.
                Soluta perferendis tenetur tempora nobis, dignissimos quos inventore nulla! Dolore necessitatibus delectus quaerat corporis vero nulla debitis nam voluptatem facilis! Error itaque necessitatibus veniam corrupti optio, quaerat architecto nobis amet.
                Rerum, molestiae voluptate architecto deleniti libero animi illo aliquam deserunt, temporibus hic placeat consectetur distinctio facilis quod pariatur debitis iure. Ipsum aut numquam praesentium, alias iure amet corporis repellat dolor.
                Optio autem necessitatibus porro? Fugiat iusto nostrum blanditiis recusandae doloribus? Cum, quo rerum corporis totam explicabo corrupti, deleniti tempora ducimus nam quaerat magnam non? Eum accusamus perferendis illum quod sequi!
                Debitis quam commodi dolore voluptatem corrupti quidem molestias fuga labore facere expedita voluptas iusto earum similique minus odit cupiditate sed, ullam ex dicta architecto est excepturi necessitatibus! Sint, amet et.
                Commodi cum excepturi magnam dolorum maiores voluptatem animi saepe sunt temporibus quos facere fugit laborum dolores nemo, deserunt qui reprehenderit accusantium quod veritatis provident culpa aliquam quidem earum? Voluptatum, quidem.
                Quasi facere ratione amet ad ipsum accusamus assumenda necessitatibus doloremque, deserunt modi hic, impedit excepturi dolores nisi iste. Ex eaque harum voluptatum rerum unde. Fuga suscipit iste soluta nobis id.
                Consequatur dicta sed culpa. Facilis error totam aliquid maxime officiis hic reprehenderit repellat praesentium minima iusto libero necessitatibus consectetur nobis nostrum, eaque saepe possimus architecto sed cumque sit! Iste, debitis.
                Reiciendis, harum, quos debitis distinctio magnam natus nulla dicta, possimus asperiores facilis sint! Nisi id cumque facere quos. Beatae magni recusandae consequatur nam illo sequi id soluta minima qui voluptatum.
                Ea, illum ab? Iure amet vero libero eveniet rem, sapiente sed culpa eius nobis ut reiciendis voluptatem sequi eligendi quidem dolorem atque quaerat illum deleniti natus, aliquam illo fugiat? Nisi!
                Molestiae neque, asperiores consectetur facere odit eaque fugiat quo nam officiis ad excepturi quis, amet error officia reiciendis aperiam? Repudiandae alias facere quisquam. Iure neque exercitationem blanditiis cum hic dolor!
                Dolorum alias sed magnam iure fugiat vero commodi aliquam perspiciatis, delectus, ipsum quae quod, est nesciunt? Est eaque nostrum possimus minima hic sed, nemo in sapiente? Quod ipsa explicabo tenetur?
                Sit labore accusantium dolorem illo esse ratione delectus saepe ad rem facere voluptatibus doloremque recusandae omnis, quisquam eos amet ipsa mollitia minima perferendis? Totam nulla quibusdam sunt dolore repudiandae vitae!
                Cumque omnis in, animi quo possimus repellat molestias nobis excepturi minus sequi inventore aspernatur ratione unde quisquam corporis dolore. Exercitationem nihil in autem voluptatum nam dignissimos velit, quam molestias quas.
                Eum, dicta dignissimos animi repudiandae nostrum, quis ratione nemo, voluptatibus quod eius perferendis possimus quia totam at accusamus. Recusandae cumque vitae minima nulla sed iste cupiditate quo alias, atque ipsam.
                Perferendis, enim qui tenetur veritatis, alias quod odio odit maiores aspernatur ab iure exercitationem suscipit, explicabo sunt tempore? Atque doloremque incidunt, exercitationem dignissimos error eveniet quo iste quisquam et id?
                Et voluptatum unde nostrum blanditiis eius modi inventore autem laboriosam necessitatibus, dolore temporibus ipsam aut corporis qui. Voluptate enim delectus ratione quidem eaque minus aliquam porro nihil quod, et perferendis.
                Itaque optio sit dolorem sunt adipisci illum, animi voluptatem? Molestias necessitatibus alias porro quibusdam repellendus odio. Cum, ut totam! Sed tenetur nobis consequuntur aperiam perspiciatis pariatur doloribus quia commodi eveniet.
                Labore perspiciatis ducimus consequatur dicta. Tempore, pariatur eligendi repudiandae perspiciatis minus unde odit deleniti velit. Delectus, optio, consequatur aut commodi distinctio eveniet dolores ab officiis fuga quasi, soluta aperiam repellat?
                Veritatis totam ducimus distinctio similique impedit, et neque error fuga architecto praesentium deserunt recusandae corporis illo repellat minus. Eaque ab iste praesentium consequatur laboriosam ipsum error eum ut accusantium! Eaque.
                Voluptatem molestias quae a hic, ducimus aspernatur deserunt at vero similique distinctio? Temporibus, modi repudiandae saepe laudantium non alias obcaecati doloribus neque exercitationem explicabo officiis eos rerum deleniti nemo tempore.
                Hic labore quo officiis dignissimos voluptatum facere accusamus, harum amet quisquam laborum sequi totam, nemo inventore incidunt! Cupiditate quidem repellendus ratione mollitia magni, necessitatibus natus inventore laborum! Dignissimos, atque velit.
                Vero, fuga exercitationem dolores id, facere ipsam perferendis doloribus esse possimus numquam reiciendis harum dicta. Facere aut tempore nesciunt sed optio est asperiores qui iste praesentium! Earum esse culpa dolore?
                Dolores maxime similique veniam quod a sequi, modi, fugiat debitis at nisi sed sint est, error veritatis! Fugiat, blanditiis. Laborum at corrupti ipsam eum inventore quae accusamus architecto aspernatur amet!
                Nam fugit eos ullam nobis quam? Excepturi earum quas in cupiditate natus, odio asperiores, placeat quasi ex accusamus, voluptatem sequi sint laudantium eius dignissimos atque tenetur? Labore odit aut itaque.
                Blanditiis eos delectus reiciendis quam quasi quas aut, reprehenderit, similique explicabo dicta quos impedit ab fuga fugit quaerat veritatis accusantium libero sint, recusandae iusto quis enim veniam. Recusandae, reprehenderit porro.
                Alias nisi non eius doloribus qui voluptas quo, quidem corporis provident quam quos dolorum veritatis quisquam esse ab hic. Deserunt voluptatibus illum architecto rem veniam dolorem similique error iste modi!
                Vel, eveniet error! Eum qui architecto sint in, harum, eaque vero accusantium assumenda ab ad beatae ducimus totam provident dicta commodi. Dolore animi, molestiae quae fuga excepturi similique sapiente eligendi!
                Natus, minima non! Dolore exercitationem dignissimos culpa odio, blanditiis voluptatum suscipit autem dolorum magnam rerum voluptates voluptatem dolorem soluta voluptate, a incidunt laudantium aliquam vel atque aut. Amet, maxime sit.
                Consequatur aspernatur error assumenda tempore, dolorum odio fuga soluta velit delectus, explicabo, nesciunt eaque aliquam hic! Modi qui eveniet quas nostrum maiores eligendi, culpa veritatis minima assumenda deserunt sed voluptates?
                At sapiente perferendis reprehenderit saepe laboriosam expedita obcaecati dolorem reiciendis amet deserunt molestiae iste consequatur, non natus hic veritatis accusamus odit? Fugiat ipsam nam cupiditate minus odit dolorem ab unde!
                Quos magni minus est quasi accusantium quidem. Sequi maiores placeat possimus quibusdam nostrum facere omnis modi, quae praesentium facilis obcaecati molestiae itaque minus neque consectetur magni deserunt explicabo porro nobis?
                Eaque nisi accusamus, velit quam autem beatae laudantium, natus vel obcaecati incidunt, ab illum sunt enim sit libero at quibusdam optio? Nemo ipsa, debitis numquam praesentium tempora nihil magnam libero?
                Praesentium animi asperiores corrupti nihil fuga dolore laudantium cum delectus fugiat et, veniam hic voluptates eligendi sunt culpa deleniti repudiandae dolores enim nostrum nam omnis nulla velit! Recusandae, labore quibusdam!
                Inventore veritatis eveniet fuga assumenda unde, tenetur ducimus vero repellat animi quisquam. Earum recusandae vel incidunt dolorum placeat exercitationem doloremque quo itaque culpa, fugiat obcaecati amet, accusamus quae, modi laudantium.
                Quod, reiciendis repellendus, facilis vel illo voluptate doloribus repudiandae deserunt natus tempore eos eligendi dignissimos harum voluptatibus quam sequi nostrum ad eveniet incidunt ipsum blanditiis ipsa. Labore et adipisci deleniti!
                Nostrum maiores odio laborum, debitis quis iure modi dolorem voluptatem corrupti architecto! Ut autem iusto et id excepturi! Iste esse laudantium corrupti ex neque odit nostrum fuga ad, laboriosam sunt.
                Saepe nesciunt perferendis at ipsam totam quibusdam beatae, incidunt quod? Qui ducimus, modi porro expedita libero fuga laudantium odit cum non quae aspernatur ad accusantium beatae ipsam quis eum commodi?
                Fugit saepe enim laboriosam. Impedit dolore minima totam cupiditate, sapiente, quibusdam repellendus beatae minus quaerat optio libero eos. Distinctio repellendus quos dicta in sint voluptas laborum maxime earum molestias sunt.
                Commodi magni, odit tempora sunt ipsam libero exercitationem aut earum asperiores necessitatibus autem officia hic vero totam sed cum accusamus sapiente. Aliquam illum explicabo quas optio tempora quia iste nam?
                Dolores facere suscipit tempore aut nostrum corrupti incidunt libero debitis minus asperiores obcaecati iusto quod voluptatum aperiam possimus nobis consequuntur natus, quis, dolorum eos! Mollitia vitae porro iste cum quas.
                Reprehenderit officia vitae consectetur, quaerat saepe molestias facere, architecto exercitationem facilis placeat fugiat aspernatur nemo quos vero iusto mollitia voluptates corrupti animi sed autem sunt esse necessitatibus repellendus aut! Libero.
                Nobis veritatis nisi architecto numquam, laborum sapiente? Rem expedita eius eos corporis mollitia illum assumenda ab omnis architecto veritatis. Eligendi aut quae placeat eaque libero pariatur, id dolor. Voluptatem, tempore.
                Est voluptatem perferendis voluptates ducimus officia nobis, incidunt fugit nemo accusantium soluta minima sapiente cupiditate quibusdam reiciendis, aspernatur totam ipsum. Sunt officia fuga consequatur temporibus repellendus asperiores optio corrupti placeat!
                Quae in autem minus sed repudiandae a ex dolorem quasi accusantium similique deserunt omnis libero ipsum exercitationem ipsam maiores numquam explicabo tempore, eos fugit. Iste in suscipit vel quidem harum.
                Impedit ab aliquid inventore nihil, quia exercitationem id provident perferendis repellendus, iste voluptatum? Fugit voluptatibus praesentium, nostrum corrupti ducimus tempora beatae cupiditate ea maiores atque odio quaerat aliquam, sint suscipit!
                Illo maxime hic maiores facilis. Eos harum voluptate nostrum repellendus? Nobis asperiores soluta blanditiis eligendi rerum? Dicta corrupti aspernatur provident rerum repudiandae temporibus quam cupiditate blanditiis, repellat molestiae. Eum, perspiciatis.
                Voluptatem quo tempore quibusdam magnam, nihil vero deleniti cumque provident neque id aspernatur similique deserunt. Suscipit velit provident temporibus nam in! Voluptatem dolorem quibusdam ipsum modi. Quod labore soluta accusamus.
                A tenetur quibusdam, aliquam laboriosam placeat sequi quod aperiam explicabo repellat, magnam nihil. Provident, ea rerum nesciunt ipsa nemo inventore cumque quis suscipit nobis deserunt itaque, ratione eaque, adipisci reprehenderit.
                Eius laboriosam eum nostrum? Tempore odit nobis neque ut minus. Temporibus tempore quaerat nostrum fugit deleniti assumenda minima sit. Minima sint quo esse magni, iste explicabo commodi modi quis veritatis.
                Dolorem provident consectetur perspiciatis et est, illum, nesciunt quisquam quis aliquid sint eius atque cum dolorum asperiores optio debitis fugit? Doloribus, iste inventore nesciunt quasi quis provident et eius sunt!
                Recusandae nemo adipisci iste aperiam dignissimos, saepe aliquid non perspiciatis, magni atque culpa dolorem magnam quas. Molestiae, accusamus iste consectetur, nesciunt eveniet adipisci quae esse dolore soluta et dolorem qui?
                Cum, odio! Ea debitis fugit dolorem vitae aut, pariatur dicta incidunt molestias, culpa odit, quas voluptas. Saepe nemo quibusdam earum quo, eius accusantium, sunt cumque, laboriosam mollitia ipsa eveniet rerum!
                Iusto ullam libero sapiente provident molestias recusandae doloremque inventore suscipit architecto totam consectetur sequi obcaecati quos repellat vel soluta voluptates maxime quas, dolore est praesentium nobis odit aliquam velit. Blanditiis.
                Quae magnam eum, sit accusamus, autem natus asperiores iusto ratione optio officia est velit laborum enim magni quibusdam veniam excepturi placeat quia porro numquam facere corporis perferendis dolor eos. Amet!
                Molestiae hic consectetur recusandae, dolores ipsa sit in ipsam excepturi aliquam adipisci, maiores eius libero sequi tempora veritatis accusantium? Nemo incidunt minus vitae ipsam sit ab cum aliquid reprehenderit labore.
                Optio architecto aut totam culpa quam amet tempora, expedita voluptatum soluta, neque perspiciatis voluptates rerum numquam esse, ratione iure consequatur inventore quia cumque ab quod alias voluptatem? Molestiae, vel quod!
                Corporis at, quae rem nostrum magnam quidem repudiandae neque aliquid. Libero, numquam, nihil laboriosam cum nam magnam fuga aspernatur alias neque nisi perspiciatis voluptate suscipit aliquam quasi ad assumenda nostrum!
                Nam, vitae officiis harum beatae atque perferendis quis iste mollitia delectus. Voluptates quidem deleniti eum illo iure dolorum sed explicabo. Qui, maxime quas officia accusantium iusto autem eum ducimus at.
                Rem ducimus quaerat voluptas, deserunt ratione sit quisquam dicta praesentium nulla blanditiis quos odit? Voluptates maxime id ad a illo, recusandae minus! Alias dolores vel soluta expedita illum quod nesciunt!
                Nulla suscipit voluptatum nihil excepturi enim distinctio veniam, odio fugiat fugit cum aspernatur delectus sit, illo aperiam alias in natus! Exercitationem magnam repudiandae consequatur explicabo eius architecto, expedita animi dolorem.
                Assumenda odit ab dolorem. Quibusdam, error ea itaque maiores, iste pariatur inventore tenetur voluptatibus fugiat eaque dolorum libero, expedita sint. Molestiae veritatis commodi quis quas architecto qui quo id sunt.
                Quidem voluptatem dolores consequuntur inventore libero fugit suscipit aspernatur unde autem, quos consectetur mollitia ad est officia esse ab vero, laboriosam facere beatae et. Corrupti quis deleniti aliquid vel sunt.
                Aliquid est hic pariatur? Eligendi dignissimos commodi neque? Earum voluptates sunt odio dolorum deserunt aperiam unde quasi autem consectetur et repudiandae aut placeat tenetur tempore eligendi, quidem veniam dicta itaque.
                Expedita reprehenderit quas nisi fuga? Est error quos, rerum porro quidem quibusdam alias. Numquam pariatur, mollitia, ut voluptatibus explicabo hic commodi cupiditate cumque, et eius repudiandae nobis quae id nemo?
                Repellat saepe tenetur id ipsam sint. A ipsam quaerat asperiores sunt expedita nobis sit, ad dolor culpa officiis veniam optio fugiat in. Incidunt, perspiciatis quaerat nobis fuga consequatur ipsa eos?
                Quaerat, molestiae consequatur sint repudiandae animi adipisci. At a enim doloribus placeat, quia pariatur vero illum nostrum, eius dolore voluptate assumenda consectetur? Autem natus accusamus temporibus culpa ratione voluptatibus hic.
                Recusandae iure quam debitis eum voluptatem omnis officia. Repellendus, ea molestiae? Quibusdam labore quam rerum eum repellendus, velit, atque laboriosam sit veritatis odio odit eligendi mollitia nostrum aliquam! Nisi, nihil.
                Labore quia autem fuga perspiciatis architecto deserunt ipsam sit laborum omnis obcaecati alias earum quos harum esse consequuntur est quidem hic sunt sint rerum aliquid corporis, expedita quod soluta. Quasi!
                Suscipit dignissimos cupiditate, non hic id repellat molestias voluptates sed, tenetur dolores laudantium maxime pariatur. Placeat inventore minima aliquid natus, consectetur, non, expedita quisquam error accusantium facere accusamus dolor qui.
                Maxime possimus cupiditate voluptatum quam, dolore nam ut cumque dignissimos, facilis similique perferendis exercitationem suscipit obcaecati at quo modi soluta rem praesentium aspernatur id maiores quibusdam sunt laboriosam accusantium. Quaerat?
                Quod sunt placeat a voluptatem dolorem quasi tempore dolor iste ut magnam! Doloremque tempora, fuga asperiores quod blanditiis delectus natus? Reprehenderit fugit amet nemo iusto ipsam quae sunt laborum possimus.
                Maiores, pariatur! Quidem excepturi vel error sunt animi, et velit at distinctio pariatur corrupti ducimus possimus est labore nostrum autem magni. Odio est laudantium voluptatibus asperiores nihil minima molestias perspiciatis.
                Dignissimos incidunt vero sapiente ipsum? Placeat rem quidem, ea similique corporis quis eum earum, quod, expedita porro a nihil possimus delectus labore. Neque odio id, est nihil itaque eligendi? Iste.
                Aliquam fugit officia nisi non obcaecati. Sed, eaque? Voluptates possimus totam laudantium nesciunt recusandae doloribus! Fugit natus nihil, obcaecati mollitia expedita eum aut minima aliquid ipsam facere veritatis dolorum doloribus.
                Neque optio at nesciunt aperiam eveniet dolore officiis qui sint accusamus. Animi, ab accusantium ad nesciunt reprehenderit facilis. Ullam tempora quos vero dolores aspernatur nobis provident rem nulla cumque distinctio!
                Veritatis itaque culpa, quas perspiciatis voluptas voluptatem sint magnam sequi! Laborum cumque suscipit, sapiente, architecto modi placeat voluptates vero reprehenderit quaerat, rem inventore. Saepe vitae amet inventore perferendis sit eligendi.
                Ea necessitatibus, laboriosam delectus culpa saepe nesciunt incidunt labore. Molestiae assumenda placeat et. Laborum quae ex, soluta laudantium nisi optio neque debitis sed atque iusto aperiam voluptatibus facilis eaque quibusdam?
                Dolor quibusdam eligendi aliquam velit reiciendis porro accusamus veniam officiis quas consequatur? Dolor cum aut corrupti pariatur quibusdam nobis asperiores assumenda, quam hic doloremque harum aliquam, sunt mollitia, et perspiciatis.
                Cum laborum sapiente accusantium, eligendi officiis est eius earum et vero autem corporis, cumque voluptatum, iure dicta vel sit eum? Hic nobis veritatis soluta impedit porro, earum quia doloribus ad.
                Beatae amet placeat dignissimos non distinctio consequuntur error! Vero quae accusantium iure sit cumque impedit dolore unde commodi doloremque earum eaque voluptate id, alias esse autem fugit reiciendis rem doloribus?
                Exercitationem vero at distinctio enim necessitatibus facilis, ullam officia quos iure eius ipsa doloremque voluptate, rem, delectus deleniti natus repellendus deserunt! Voluptas omnis voluptatum vel impedit, soluta optio nihil. In.
                Tenetur esse, molestias ducimus totam alias itaque repellat, quis iste ipsam, sint sapiente delectus. Pariatur illo quas dolores eius, consectetur voluptatem provident sapiente rem voluptate iste eos doloribus sit tenetur!
                Provident architecto nemo possimus optio laborum omnis voluptatibus, facilis officiis eligendi quisquam delectus vero est corporis consectetur ratione fuga? Nihil qui magni sequi est optio iure cumque eos eligendi error!
                Repellat nostrum perferendis ratione eum beatae at quis a eveniet commodi modi delectus nemo ipsa dolore doloribus facilis saepe, cum culpa illum amet autem tenetur enim! Eveniet magni illo et.
                Dolores, repellendus incidunt aliquam porro necessitatibus illo ab facere quisquam maiores, qui aspernatur? Exercitationem, quae asperiores, nostrum maiores, expedita odio odit quas ipsum est optio hic numquam velit. Quasi, impedit?
                Ratione suscipit quam, nisi animi rem dolore ad quae ex aspernatur sunt corporis nostrum quasi a! Rem rerum laboriosam impedit corrupti, voluptates facilis commodi debitis excepturi temporibus itaque odio iure.
                Cum incidunt iste ab id recusandae sapiente necessitatibus minus accusamus natus, aliquam at minima veniam eos autem saepe tempora pariatur eligendi hic molestiae dicta reprehenderit quisquam asperiores? Consequuntur, voluptates molestiae!
                Quasi dolorem aspernatur deleniti odit repudiandae in repellat eum. Soluta expedita dicta minus asperiores laboriosam accusamus, nihil atque repellendus cupiditate saepe? Voluptatem vel earum error tempora corrupti odit in tempore.
                Architecto dolor laboriosam aspernatur beatae earum quam laborum vitae, exercitationem voluptate laudantium! Iure ex cumque molestias quod ad, rem eius obcaecati nulla, quaerat quo quas possimus id, eveniet ducimus libero.
                Molestiae voluptate, neque quis cumque accusantium delectus eum numquam officiis reprehenderit praesentium explicabo illum ipsum rerum quo dolorem ut voluptatibus totam pariatur nostrum minima facilis animi commodi consequuntur. Illo, et.
                Accusantium, veniam tenetur laborum libero nihil numquam cumque animi ut aspernatur sapiente labore eaque, officia nulla, veritatis praesentium esse optio placeat mollitia sequi quis. Placeat recusandae fuga provident illo repudiandae.
                Corporis maiores, excepturi eum odio sit, sapiente facere iure architecto debitis omnis quibusdam cumque autem deserunt est explicabo voluptates saepe cupiditate suscipit optio at deleniti? Similique aliquid nostrum soluta eos.
                Excepturi distinctio consectetur dolor rerum magni modi voluptate eligendi vitae, quibusdam repudiandae aspernatur sapiente quasi nemo dignissimos ab blanditiis aliquam suscipit numquam nulla obcaecati voluptatum earum nisi corrupti illum. Placeat.
                Suscipit nesciunt omnis, velit laudantium dignissimos neque debitis deserunt asperiores, ipsa, nostrum ad impedit incidunt quidem aut. Nulla, a nam quas odit ad quisquam, sapiente, veritatis aut debitis qui numquam?
                Veritatis quaerat, corrupti minus eligendi provident doloribus illum atque. Nihil sint accusamus eligendi error quasi quia facilis cupiditate similique, laborum necessitatibus culpa itaque, quae asperiores officia nulla maiores praesentium aperiam!
                Incidunt, enim ipsa facere rem perferendis numquam accusantium dicta, error eveniet magnam pariatur repellendus mollitia iusto aliquam, et ipsum! Vitae totam id error dicta iure alias optio rem nam earum.
                Ratione odio minus ea illum possimus. Nobis qui quo magni? Labore quia quis ab voluptatibus amet temporibus eum mollitia accusamus tenetur natus, repudiandae, voluptatum, dolorum laudantium nesciunt eaque odio necessitatibus?
                Sequi repudiandae debitis odit pariatur dicta rerum in odio ad nostrum. Ullam, dolor. Excepturi sunt animi quisquam tempora facilis nesciunt quasi eos, est molestiae debitis quod, deleniti mollitia! Eveniet, possimus.
                Dignissimos tenetur illum suscipit ab, tempore fuga dolore magni non velit eligendi maiores neque eos quas sed quo officiis a vitae commodi quasi laboriosam adipisci. Distinctio odio voluptatem minus! Delectus?
                Vitae culpa a asperiores ex numquam alias repudiandae vero quidem voluptatem sed doloribus est neque sint nostrum saepe nulla, quasi dolores atque blanditiis, minus ipsa dolorum consectetur quos. Vero, harum.
                Id doloribus et, impedit harum excepturi sit ab quidem possimus maxime perferendis optio, soluta tenetur? Voluptatibus omnis fugit nemo. Doloremque reprehenderit maiores eius voluptatem deleniti vitae itaque soluta, consequatur laborum?
                Cum corporis reprehenderit itaque, tempora totam natus, voluptatem, tempore libero quam illo cupiditate illum quas sed? Quae tenetur, magni quas neque dolor voluptatem? Totam fugiat ullam dolorum laborum asperiores quia.
                Totam quaerat labore consectetur necessitatibus! Distinctio praesentium laborum vel earum quam eius delectus vero doloremque enim est omnis, ipsum velit, sed rem voluptatum tempora nihil assumenda unde quibusdam tempore illo.
                Iste minus odit pariatur nobis cum, minima architecto repellat ea tempore beatae soluta harum ratione quasi inventore aliquam. Optio voluptatum suscipit nesciunt cumque sit, ipsam neque repudiandae iure obcaecati nobis!
                Nostrum ea voluptas, tenetur consequuntur esse ab neque, labore fugit, animi perferendis reiciendis voluptate sint debitis quibusdam dicta soluta cum tempore distinctio consequatur excepturi voluptatum adipisci porro. Debitis, mollitia doloremque.
                Eveniet quam ut inventore nesciunt voluptatem quos at illo, labore fugiat nulla impedit illum deleniti dolor adipisci, magnam similique! Voluptatibus doloribus ipsum autem praesentium possimus voluptas expedita quis distinctio sapiente.
                Nihil fugiat asperiores itaque modi deserunt exercitationem nam rerum at amet. Est id et quibusdam eligendi, aspernatur assumenda exercitationem dolorum hic in ut dolorem aperiam quaerat dignissimos soluta quod nostrum?
                Deleniti, qui ipsam doloribus facilis nulla minus totam. Libero fugiat voluptates officiis et facilis velit fugit animi iste, reprehenderit repellat ullam eaque quidem laborum culpa? Officiis facilis repellat fugiat iste?
                Earum, molestias. Asperiores tenetur exercitationem obcaecati perferendis, aspernatur quo ipsam reiciendis saepe iure ducimus alias praesentium rem aliquid voluptas nesciunt, provident sapiente dignissimos, repellat quia sunt quidem tempora natus? Eos!
                Facilis dolor omnis vitae natus sapiente iure quas aperiam nesciunt id delectus dolores reprehenderit corrupti quibusdam, aspernatur a eos alias molestias neque eum itaque fugit! Eaque asperiores atque quibusdam mollitia.
                Fugiat id quos eius et dolor molestiae necessitatibus dolore nobis illum sequi doloremque porro delectus consectetur, veritatis possimus rem eveniet laborum sapiente dolorem voluptate temporibus adipisci ex pariatur. Amet, fugit?
                Consequuntur debitis cumque qui sed odit facilis dolor ab nobis iste officia ipsa molestiae ducimus reprehenderit quo alias, et quae, rem a. Reiciendis perspiciatis dolorum in cum! Optio, culpa voluptates!
                Nulla, tenetur! Excepturi neque adipisci natus vel at asperiores laborum, ea rerum maiores soluta ab, facere nisi? Inventore aliquid ut temporibus ducimus quam molestias delectus aliquam nostrum obcaecati? Autem, dolore!
                Esse accusantium eaque modi quos. Sed facilis aliquid mollitia accusantium dignissimos officia eum, quidem nihil laborum necessitatibus veniam totam molestias dolor minus fugit aperiam numquam velit placeat illum atque. Cumque.
                Hic adipisci et tempore vel sunt beatae animi voluptate doloremque excepturi id neque harum quis ab sint enim molestias repudiandae ex cupiditate, facilis alias perferendis esse minus! Exercitationem, corrupti ea.
                Fugiat, ea vitae. Quam, dolor repellat impedit debitis repudiandae cumque perspiciatis aut id reprehenderit! Repudiandae voluptatibus fuga deserunt! Aspernatur facilis minus ipsam veritatis sapiente neque numquam id a optio laudantium.
                Eaque officiis in quis sunt, laborum at, dolorum, placeat voluptas eius dignissimos odio! Veritatis beatae aut hic, voluptas, quasi itaque tempore temporibus exercitationem sunt in illo repellendus iure odio quis.
                Cupiditate, accusamus mollitia consequatur quo, eum temporibus soluta ullam, esse veritatis repellat corporis iste tenetur pariatur est maiores! Nisi quidem autem necessitatibus voluptatem tenetur doloribus itaque rem odit assumenda accusamus.
                Blanditiis aspernatur voluptate eveniet culpa, dolorem maiores quo cupiditate amet dignissimos quas saepe exercitationem sapiente vero esse laudantium neque distinctio consectetur asperiores animi officiis suscipit obcaecati, inventore iste voluptates. Ex!
                Fugit rerum aspernatur facere ipsum accusantium explicabo sed voluptatum, tempora quaerat minus, dignissimos quia ullam sapiente voluptates quo, non tenetur. Eius id aliquid ipsam quis deserunt illum dignissimos obcaecati dolorum.
                Voluptates, corrupti ullam fugiat deserunt placeat aliquam eveniet excepturi necessitatibus dignissimos minus reprehenderit odit animi recusandae quasi repudiandae voluptatibus sapiente doloremque? Iusto asperiores culpa ullam facere cum blanditiis ipsum repellendus!
                Velit libero ab eligendi, dolore accusamus quos recusandae quasi incidunt eum similique alias sunt reiciendis vero, consequuntur, aut ipsa praesentium et reprehenderit quam fugiat cupiditate illum tempora rerum. Quidem, laudantium!
                Tenetur culpa a quod eius atque veritatis quisquam nemo sapiente, magni est sed, neque natus quaerat placeat delectus, mollitia architecto ea consequatur quibusdam libero. Architecto deleniti dolores adipisci ipsa accusantium!
                Quaerat ducimus maxime esse architecto adipisci dignissimos tempore ipsam iure sequi ab, sed soluta, perspiciatis temporibus id commodi maiores dicta expedita ipsum quisquam blanditiis consequatur quis fugiat asperiores amet. Dolorum?
                Voluptatum saepe officia excepturi placeat culpa. Iusto corrupti nemo eligendi delectus commodi vitae velit blanditiis vero dolor minus ullam accusamus cum nulla adipisci quisquam non harum, a beatae nisi. Nobis.
                Numquam quasi assumenda doloribus corrupti doloremque odio accusamus sequi illo ut libero tempora, temporibus id minima? Unde optio porro placeat repellendus eaque veritatis error quas ratione eum, ea expedita aut.
                Vel repellendus hic eligendi, neque similique natus asperiores delectus nulla ducimus laudantium. Nemo perferendis adipisci perspiciatis omnis pariatur cupiditate cum totam dolorum amet nisi vel, delectus nobis ut libero rem!
                Praesentium, odit, a magnam optio amet aliquid numquam ipsam necessitatibus animi eius rem? Temporibus beatae doloremque pariatur fuga fugiat qui excepturi adipisci necessitatibus rerum, tempore reiciendis, error ullam nulla repellat.
                Assumenda nemo aliquam ratione iusto, autem facere architecto aliquid hic expedita molestias pariatur praesentium at, illo, nisi in provident non error perferendis dignissimos quaerat est tenetur ea repellendus. Vero, saepe.
                At illum temporibus modi eos? Modi labore illum cum, perferendis corrupti accusantium suscipit tempore a nobis ad ducimus officia incidunt, alias unde, iste eius autem aliquid nulla dolores dolore aut.
                Nemo voluptatem quod itaque aspernatur ut. Obcaecati consequuntur ipsa ipsum voluptatum assumenda in ducimus dignissimos, repellat officiis sunt. Eaque esse reiciendis dignissimos fugiat laudantium adipisci totam eum eius aut doloremque?
                Expedita aspernatur fugit consectetur facere architecto quia laborum possimus, vitae voluptatum alias blanditiis veritatis corporis quasi sit! Aperiam minima voluptatem illum, consequatur quae, qui quisquam laboriosam perferendis alias possimus quidem?
                Deserunt et a quibusdam illum dolorem ab debitis tenetur inventore atque eius, repellat magni veniam ex exercitationem. Est voluptate eligendi consequatur, delectus odio minima inventore similique. Saepe eos quis rem?
                Debitis laudantium quaerat voluptas beatae dolore illum tempore nihil eum autem porro sapiente voluptates a veniam dolores, odio alias aut, iure molestiae. Ratione cum exercitationem et explicabo molestias dolor neque.
                Dignissimos dolorum voluptate alias atque provident cupiditate incidunt dolores nisi perspiciatis autem, numquam nihil laudantium esse magnam, voluptates corporis quia explicabo eos aspernatur sapiente omnis earum quae? Impedit, ex iste.
                Quisquam qui nobis accusantium delectus. Similique nesciunt provident commodi aspernatur pariatur praesentium nihil, harum sint beatae repudiandae odio, necessitatibus architecto aliquid dicta tenetur eligendi quia odit est modi ipsum cumque?
                Laborum ipsa cum eligendi quod voluptates eaque animi esse expedita officia? Ex, eaque porro unde nostrum aliquid assumenda harum, eius architecto dolores deserunt autem libero dolore voluptatibus deleniti optio sit!
                Labore sed blanditiis architecto error accusantium unde possimus in quos ipsa saepe fuga illum, rem tempore aliquam accusamus. Facere quas quidem reiciendis animi earum laboriosam beatae eius odit a error?
                Aliquid consectetur, neque vitae cum necessitatibus alias excepturi. Quibusdam, sit voluptatum libero deserunt ab qui, pariatur at aliquid voluptates eius iusto repudiandae commodi consectetur. Ut, eos nemo. Sunt, provident quos.
                Eius cumque odio id voluptas, saepe itaque, tempora architecto iusto necessitatibus dolor dolore sit earum commodi nam. Doloribus libero nemo excepturi minus dolor, magni ut facere earum, architecto ipsam expedita.
                Excepturi eveniet voluptatem possimus, impedit eos doloremque, commodi quisquam unde tempore, vel perspiciatis velit! Libero eum, quasi eaque laborum asperiores blanditiis, repellendus voluptatibus maiores eos sapiente pariatur quos iure incidunt?
                Delectus iure sit adipisci, sequi tempore eligendi? Sint dignissimos placeat eum distinctio repudiandae modi nulla architecto corrupti nam voluptatibus, doloremque iure quisquam consectetur quaerat commodi deleniti inventore corporis quae sed?
                Accusamus ad dicta, autem, debitis maiores esse, iure facilis ea eum minus distinctio corrupti. Ullam sapiente cumque voluptates, molestias similique est facere ex at praesentium voluptas numquam, rerum repudiandae deleniti.
                Fugiat dolorum voluptas numquam, exercitationem, dolor veritatis placeat sint eos saepe tenetur accusantium at illum debitis voluptatem impedit blanditiis et veniam! Quos, ratione ea nobis amet et voluptatum sunt quibusdam.
                Ipsum itaque corrupti libero accusamus, culpa tempore architecto aspernatur quod nihil quasi eius excepturi iure sequi sapiente vitae assumenda, neque reprehenderit aut dicta omnis voluptates autem hic dolorum vel? Cupiditate!
                Ipsum, reprehenderit ut dignissimos rem quam itaque, modi ad laudantium ab ducimus doloremque rerum. Fugit dicta non cum nostrum nesciunt molestiae maxime possimus, dolores asperiores at quaerat? Quos, officia quisquam?
                Consectetur quasi repellendus dicta a quaerat quo totam sapiente, debitis soluta eum ducimus ea mollitia ullam quae impedit, iure pariatur sed reprehenderit maxime repellat? Accusamus velit libero beatae rem amet?
                Explicabo numquam dolorum ab enim aliquid illo delectus voluptatibus. Animi temporibus enim quam porro quia possimus tempore minima nam magni consequuntur illum ut tempora sed fuga nesciunt, rerum, veniam cupiditate.
                Animi non dolorem ducimus repellendus pariatur voluptatibus odit laudantium reprehenderit, quos voluptas harum atque asperiores unde voluptatem necessitatibus quisquam nesciunt perferendis dignissimos recusandae suscipit rerum quia. Corporis repellat magnam alias.
                Sit ex est delectus ipsam itaque libero? Labore ab saepe aspernatur nisi dicta odit minima facere sed! Aperiam iste nam et dolorum doloribus expedita, architecto maiores illo, ducimus reiciendis id!
                Deleniti, labore fuga in modi qui eos provident. Eos nihil, saepe corrupti facilis laborum sequi similique architecto quasi alias! Vel maxime repellat animi dolore earum autem fugit recusandae dolores et!
                Deleniti esse a impedit animi dolore eum pariatur praesentium optio temporibus libero, officia ipsum recusandae quae veritatis obcaecati et nisi rerum iure ea iusto aliquid in veniam quia magnam. Facere.
                Aspernatur itaque repellendus at similique rerum reiciendis deleniti id praesentium enim eius! Atque nobis mollitia cumque voluptatem autem, reiciendis quae tempora aliquid esse ut, suscipit vel sapiente, placeat cum deleniti!
                Non veritatis accusantium laboriosam officia, aperiam quo aspernatur eveniet veniam porro quae atque alias. Quos repudiandae error odio ex beatae enim, optio quisquam delectus aperiam commodi cupiditate, dolorum officiis dolore?
                Sunt, vero. Quos suscipit enim repudiandae perspiciatis voluptatibus sapiente, sunt corrupti pariatur harum odio incidunt velit obcaecati eum sint quibusdam dolore tempore natus inventore officia! Ad modi beatae fuga vero.
                Eius maiores illum veniam eos praesentium hic, laboriosam reprehenderit asperiores, rem voluptates cupiditate at amet! Rem accusantium ipsa quam excepturi distinctio doloremque laboriosam hic recusandae quo. Placeat in asperiores tenetur.
                Tempora dolorem nesciunt eveniet deserunt consectetur at expedita doloremque amet eligendi! Cupiditate nemo, earum repudiandae repellendus quod esse error dolorum adipisci laudantium nobis, totam ullam assumenda consequuntur vero aperiam commodi?
                Aspernatur perspiciatis accusamus, aliquam cupiditate, eveniet fugiat consequatur exercitationem est perferendis, facilis necessitatibus autem optio adipisci. Harum dolorum similique itaque, eum culpa perspiciatis corrupti ullam sed laudantium quaerat provident dignissimos!
                At voluptatum ab error perspiciatis. Doloribus aut expedita fugit nobis quis voluptatem quas cum inventore, exercitationem neque modi. Neque magnam beatae quae in dolor. Et necessitatibus sapiente praesentium consequatur labore.
                Porro cumque in sed, temporibus eveniet exercitationem excepturi doloremque dignissimos repellat sunt, eius perspiciatis ducimus quibusdam quisquam, repudiandae ea corrupti similique ipsa iusto illum asperiores! Fugiat nihil magnam minima nisi.
                Tempora, totam eligendi labore atque similique quod molestias hic! Quo, natus est? Aperiam, molestias, tempore consequatur laboriosam enim atque cupiditate minima officia, nulla eaque sit ut facilis itaque exercitationem culpa.
                Eveniet repudiandae voluptatem beatae ipsam, alias delectus, dolores, nostrum explicabo reiciendis magnam dignissimos vel necessitatibus accusamus voluptates mollitia. Maiores nam, quasi ipsa temporibus totam repudiandae consectetur perspiciatis vitae omnis natus?
                Quos, expedita aliquam rem consectetur quia necessitatibus maxime minima voluptate quis a nam magni quas. Temporibus enim optio illum officia magni, cupiditate inventore quasi eaque impedit, ad provident, doloribus vel.
            </div>
        </div>
    );
}

function FormDetection({ ctx }: { ctx: OFormContextProps; }) {
    const isWeb = useAtomValue(ctx.oAllAtoms.options.isWebAtom);
    const formIdx = ctx.oAllAtoms.options.formIdx;
    return (
        <AccordionWithTrigger name='form-detection' formIdx={formIdx} triggerText="Screen detection">
            {isWeb
                ? <DetectionContent_Web ctx={ctx} />
                : <DetectionContent_W32 ctx={ctx} />
            }
        </AccordionWithTrigger>
    );
}
