export const tooltips = {
    baloonCount:         /**/ "Specifies the number of times the balloon help is shown when logon screen displays.",
    autoPrompt:          /**/ "Prompts to verify your identity immediately after logon screen displays.",
    autoPromptReload:    /**/ "Prompts to verify your identity upon browser reload.",
    lockoutFields:       /**/ "Prevents user from typing data in logon fields.",
    templateName:        /**/ "Specifies a managed logon name for a logon screen.",
    userHint:            /**/ "Text shown to the user when a screen is being automatically specified.",
    description:         /**/ "Text shown to the user to describe screen.",
    quicklinkName:       /**/ "Specifies the name to be displayed in One Touch Menu.",
    quicklink:           /**/ "Specifies the URL of the page loaded by Quick Link",
    windowCaption:       /**/ "Specifies the caption of the logon screen window.",
    extMatch:            /**/ "Extended Match Fileds\n(not for a web applications)",
    emuMatch:            /**/ "Terminal Emulator Screen Match\n(for terminal emulator applications only)",
    matchOnOff:          /**/ "Enable URL matching\r\nIf window caption is the same for multiple Web sites, URL matching can be used to resolve any ambiguity.",
    matchUrl:            /**/ "Specifies rules for detecting matching URLs.",
    monitor:             /**/ "Monitor for any changes to the screen, when the caption and/or URL may be insufficient to uniquely identify the screen.",
    optionsNeedQl:       /**/ "Specifies whether this logon screen appears in the Quick Links list.",
} as const;
