// This file is automatically generated by i18next-cli. Do not edit manually.
import Resources from './resources';

declare module 'i18next' {
  interface CustomTypeOptions {
    enableSelector: false;
    defaultNS: 'translation';
    resources: Resources;
  }
}