
export function LongPanel() {
    return (
        <div className="p-2 h-full">
            Lorem ipsum dolor, sit amet consectetur adipisicing elit. Consequuntur neque repellendus voluptas voluptates sed possimus. Itaque debitis praesentium, minima reiciendis voluptas facere delectus exercitationem aspernatur magni animi architecto quam deserunt!
            Earum rerum nesciunt enim sequi deserunt laborum quas delectus eveniet asperiores magni repellendus facilis explicabo dolor quo, quia veniam sunt minima necessitatibus animi iste vitae incidunt similique dignissimos? Nulla, accusantium.
            Ullam repellat explicabo ipsum ipsam aliquam. Culpa id, repudiandae nihil, aspernatur tempora saepe laborum suscipit quam nemo eaque dolorem voluptate aut laudantium enim beatae cupiditate animi vero minus quae odio.
            A numquam ab odit vitae libero aliquam reiciendis, quidem, laborum explicabo ratione consectetur doloribus! Eaque consequuntur rem nisi, quae veritatis et omnis enim dolorem unde eveniet molestiae tenetur. Perferendis, est?
            Quas beatae magnam voluptate excepturi, modi quibusdam assumenda voluptatem nihil incidunt eaque ab doloribus reprehenderit aliquid labore, animi fugit quos provident. Doloribus, pariatur. Nihil laboriosam voluptatum, adipisci fuga necessitatibus quasi!
            Quo atque nesciunt ipsam. Tempore culpa voluptatibus ipsum, harum sint aut maxime laudantium laborum ab assumenda! Quo expedita voluptatibus asperiores maxime explicabo corrupti, at praesentium? Commodi debitis deserunt consectetur ipsum.
            Aspernatur molestiae consequatur doloribus architecto veritatis officia, magni, inventore ab quam temporibus explicabo ex. Itaque aliquam, repudiandae sunt praesentium suscipit atque, sapiente dolor necessitatibus expedita vero veniam! Soluta, non corporis?
            Voluptatibus iusto odio vero incidunt delectus, laborum provident quasi corrupti aspernatur ipsam maxime assumenda corporis doloremque consequatur eaque facere aperiam sint. Voluptate deleniti corporis, eveniet optio laborum hic aperiam laboriosam?
            Temporibus cupiditate ad mollitia in doloremque aperiam optio, quisquam maiores, adipisci natus quas eligendi praesentium corporis quidem commodi recusandae atque. Officia molestias totam sunt quis temporibus porro laborum consequuntur at?
            Quisquam voluptatum laborum sit recusandae fugiat laudantium, officiis illo beatae aperiam. Vero at, aliquam dolor commodi voluptate quia neque fuga eius corrupti possimus, ratione culpa quibusdam molestias rerum distinctio assumenda!
            Expedita reprehenderit harum cupiditate temporibus error incidunt quaerat, tempore tempora dignissimos sequi animi aut, ut accusantium nihil quam maiores consectetur voluptates fugit dicta est, officiis praesentium vero voluptate. Sequi, quas?
            Aliquid sed debitis pariatur corporis! Corporis deleniti qui voluptatem et aliquid, dolorum sed, reiciendis ea iste sint, nostrum numquam repellat vel at nam temporibus enim? Repudiandae nisi quasi alias sequi.
            Quae soluta maiores dolor quas debitis, itaque inventore illum excepturi pariatur hic earum illo nemo quod! Expedita nostrum maxime debitis eos repellat magni tempore minima quia. Dolor facere id eligendi?
            Pariatur hic quos incidunt minus voluptates magni, recusandae, earum ullam accusamus esse necessitatibus, asperiores fugiat eum possimus ratione tempora similique corrupti assumenda nihil. Iure consequuntur ad minima dolore in amet.
            Repudiandae a eum harum. Explicabo tempore dolor voluptate maiores molestiae nostrum ratione fugit quis excepturi. Quasi officiis repudiandae saepe dignissimos eius? Magnam id nulla rem officiis animi voluptates libero veritatis.
            Sit perspiciatis nulla voluptas, animi ratione nemo sint atque adipisci dicta, consequuntur iusto maxime quia officiis nam itaque ad ullam quidem? Maxime tempora dolorum ea excepturi quos dolor rerum in!
            Ducimus nostrum voluptas perspiciatis nemo magnam atque at, recusandae cupiditate debitis unde alias consequuntur optio, dolorum porro eum placeat assumenda, magni officia. Est excepturi quis laudantium, aspernatur facilis sapiente quibusdam?
            Suscipit sequi dolore neque, laudantium expedita recusandae libero a ipsa maxime magnam placeat ratione delectus dolores vero. Delectus aspernatur ullam explicabo inventore unde fugiat laborum repellendus, accusamus odit nulla deserunt.
            Accusantium perspiciatis vel asperiores quidem, praesentium sapiente rerum adipisci, sed repellendus aperiam inventore consequatur odit a placeat numquam iste nam! Laudantium magni eum quo alias quisquam et explicabo recusandae nostrum?
            Cumque autem veritatis voluptatum facere vero, omnis illum? At ea sint laborum eligendi. Dolorem laborum, aut atque libero ducimus dolor nisi corrupti doloremque placeat odit eum amet maxime velit. Numquam.
            Maiores quae dolores aut amet et quaerat commodi accusantium magni nulla numquam vero eligendi quod laudantium nemo, est suscipit nihil esse! Eos porro quasi at numquam minus esse quas debitis.
            Reiciendis, eaque quia, ipsam, deleniti ab maiores inventore iure culpa ipsum repellendus dolores laudantium? Iure a ex animi quasi! Dolore, neque non. Dolore ratione, nobis ullam veniam eius labore eum?
            Nihil tempore porro atque facilis est. Nesciunt, distinctio neque? Impedit at dolorem fugit neque voluptates itaque modi. Veritatis velit cupiditate nobis iure corporis aliquam voluptate esse, iste fugiat, enim odio!
            Soluta error, illum similique minus aut ratione enim maiores labore! Dolorum error sit voluptate? Totam similique illo suscipit dolorum deleniti excepturi, laborum quos in? Quam dignissimos cumque delectus debitis sed?
            Impedit eum voluptate dignissimos, quae sequi adipisci temporibus excepturi nam officiis quo. Mollitia nisi sapiente ratione, repellat perspiciatis quo enim minima. Nisi odio libero voluptas illo, provident totam iste magni?
            Temporibus, alias molestias quo omnis exercitationem, magni in qui assumenda quidem similique eius dolor voluptatem perferendis numquam. Nihil, eos culpa nemo blanditiis nesciunt fugit obcaecati, in, harum similique voluptatibus neque.
            Architecto, laborum molestias esse, sed veniam aut illo eaque illum ea quam deleniti ut, id minus obcaecati asperiores delectus! Accusamus delectus rem magni sapiente nemo suscipit sint quisquam nostrum rerum.
            Perferendis omnis doloribus veniam quod ex? Nisi beatae, facilis sit, numquam reiciendis repudiandae eaque tempore labore adipisci pariatur, dignissimos totam corporis nobis aut doloribus vel dolorum recusandae laudantium incidunt cupiditate.
            Illo repellendus, nesciunt ullam repellat architecto similique totam magni nihil porro recusandae quo ut cupiditate fugit aut. Magni deleniti nemo consectetur tenetur minus nihil labore aspernatur, quam cumque libero omnis!
            Numquam doloremque mollitia aut. Doloribus neque amet sapiente quis, ut at expedita cumque tempora ullam nam, eaque quod nulla quos et numquam consequatur quaerat! Fugiat ipsa modi ipsum iure itaque.
            Asperiores laboriosam perferendis atque ut earum ea dolor, molestias aperiam! Tempora at repellendus nemo expedita, enim exercitationem quidem atque, ipsa consectetur aliquid repellat laudantium ad cum velit. Qui, saepe error?
            Possimus unde eligendi, facere quisquam veritatis, ad quidem pariatur minus excepturi magnam sunt voluptas necessitatibus aut. Tempore est optio repellendus, dolores, facilis, enim possimus consequuntur dignissimos consectetur eius modi? Pariatur!
            Cum eligendi architecto exercitationem, excepturi aperiam id necessitatibus. Explicabo maiores perspiciatis similique veniam eius quis ipsa distinctio delectus quas, animi minima praesentium molestiae. Nostrum ullam qui numquam sit quae unde!
            Sint, animi quaerat natus quibusdam consectetur laboriosam quidem aliquid explicabo temporibus hic ex? Quae qui asperiores quia nulla ducimus voluptates, iste voluptatum eius architecto hic sunt, aspernatur repellendus fuga omnis.
            Dolorum eius in quidem aspernatur, porro rerum reprehenderit cum voluptatum quod. Rerum optio necessitatibus, temporibus et velit reprehenderit veniam quo ipsam nobis a sint saepe hic, placeat adipisci aut quidem!
            Repudiandae, aperiam repellendus. Doloribus tempore, dignissimos fugit sint inventore provident asperiores officia saepe maxime voluptas! Illo voluptatum alias a distinctio ex labore commodi. Perferendis enim ab, autem laudantium dicta sequi.
        </div>
    );
}
