export * from "./0-all";
export * from "./1-get-target-window";
export * from "./2-get-icon";
export * from "./3-get-controls";
export * from "./4-get-manifest";
export * from "./5-get-screenshots";
export * from "./6-highlight-control";
export * from "./6-highlight-window";
export * from "./7-drag-and-drop";
export * from "./8-extra-info";
export * from "./9-types";
export * from "./10-general-info"
export * from "./11-perform-command"
